baseurl = "https://mutabl.xyz/"
languageCode = "en-us"
title = "Tom's Blog"
theme = "hugo-steam-theme"
disqusShortname = "spf13"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 10

[params]
	title = "Tom's Blog"
	subtitle = "Random musings about code that probably works."
	copyright = ""

	# You can choose between green, orange, red and blue.
	themecolor = "green"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Tom Pinnock"
	bio = "programmer of things - likes coffee"
	description = "Some coding stuffs and shit like that."
	
	# Link your social networks (optional)
	location = ""
	twitter = "tompinn23"
	linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "tompinn23"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
